cupsDeck = {
    "Ace of Cups" ,
    "Two of Cups" ,
    "Three of Cups" ,
    "Four of Cups" ,
    "Five of Cups" ,
    "Six of Cups" ,
    "Seven of Cups" ,
    "Eight of Cups" ,
    "Nine of Cups" ,
    "Ten of Cups" ,
    "Page of Cups" ,
    "Knight of Cups" ,
    "Queen of Cups" ,
    "King of Cups" ,
}