-- This file is AUTOMATICALLY GENERATED by generate_card_data.py
-- DO NOT EDIT THIS FILE MANUALLY!

CARD_DATA = {
    ["Ace of Wands"] = {
        correspondence = {"The first breath of flame… untamed, divine, and aching to become."},
        upright_keywords = {"inspiration", "spark", "new passion", "creative force", "initiative", "awakening", "potential"},
        reversed_keywords = {"false start", "burnout", "creative block", "hesitation", "scattered energy", "missed opportunity", "apathy"},
        upright_fortune = {
            "A new fire stirs. Try not to burn down the map.",
            "Desire awakens. Your muse is cackling already.",
            "Spark found. Chaos scheduled shortly after."
        },
        reversed_fortune = {
            "You reached for fire, but grabbed smoke.",
            "The wand twitched. You blinked. Nothing happened.",
            "The spark fizzled. Now the ashes look bored."
        },
    },
    ["Two of Wands"] = {
        correspondence = {"Mars in Aries. Fire peers past the threshold, a hunger for what still flickers beyond sight."},
        upright_keywords = {"planning", "vision", "future potential", "decision-making", "personal power", "boldness", "ambition", "crossroads"},
        reversed_keywords = {"fear of change", "indecision", "playing it safe", "lack of direction", "unfulfilled plans", "hesitation", "restricted vision", "missed chance"},
        upright_fortune = {
            "A world awaits. But first, a dramatically thoughtful pause.",
            "Choice stirs. One hand on the past, one itching for elsewhere.",
            "The plan simmers. The fire stretches toward tomorrow."
        },
        reversed_fortune = {
            "The path was there. You brought a blindfold and a mirror.",
            "So many options. None of them picked you back.",
            "You dreamed big... and then tripped over logistics."
        },
    },
    ["Three of Wands"] = {
        correspondence = {"Sun in Aries. A flame sent forth still longs to return. The horizon remembers its source."},
        upright_keywords = {"progress", "foresight", "expansion", "momentum", "long-term vision", "opportunity"},
        reversed_keywords = {"delays", "disappointment", "lack of progress", "poor planning", "shrinking vision", "missed ships"},
        upright_fortune = {
            "The future waves from afar. You squint, unsure if it's friendly.",
            "The path ahead burns bright. But yes, you'll still stub your toe at least once.",
            "Ships return. Some carry gold, others carry lessons. Or unpaid invoices."
        },
        reversed_fortune = {
            "Planning? Glorious. Doing? Suddenly you're rearranging candles again.",
            "You waited for a sign. The sign waited for you to stop waiting.",
            "A ship lost at sea. Or maybe you just forgot where you parked it."
        },
    },
    ["Four of Wands"] = {
        correspondence = {"Venus in Aries. A hearth is lit, and voices gather. Joy, fleeting, but real as smoke in the wind."},
        upright_keywords = {"celebration", "harmony", "homecoming", "joy", "stability", "shared success", "foundation", "union"},
        reversed_keywords = {"instability", "tension at home", "canceled plans", "fleeting joy", "disconnection", "lack of support", "disharmony"},
        upright_fortune = {
            "A rare stillness, dressed in laughter. Don't question it, just dance.",
            "You made it. The cosmos throws a party. No one RSVPs, but they all show up.",
            "The hearth is warm. Spirits nod approvingly between mouthfuls of cake."
        },
        reversed_fortune = {
            "False joy rings hollow. The echoes are doing their best.",
            "Home doesn't feel like home. Maybe check for metaphysical termites.",
            "You almost relaxed, but the universe noticed and immediately sent a test."
        },
    },
    ["Five of Wands"] = {
        correspondence = {"Saturn in Leo. When too many flames dance, the shadows grow bold. A test of will and spark."},
        upright_keywords = {"conflict", "competition", "chaos", "tension", "differing views", "challenge", "provocation", "ego clash"},
        reversed_keywords = {"avoidance", "inner conflict", "suppressed anger", "retreat", "passive aggression", "unresolved tension", "false peace"},
        upright_fortune = {
            "The forge of friction: if you're not burning, you're not learning.",
            "So many cooks. So much fire. The soup is now an inferno.",
            "Conflict brews, the spirits sips the tea. They love a little drama."
        },
        reversed_fortune = {
            "Suppressed sparks smolder weird. Don't let your insides become a kiln.",
            "You backed away from the fight. The fight followed, wearing slippers.",
            "You avoided the clash. And now you're arguing with mirrors."
        },
    },
    ["Six of Wands"] = {
        correspondence = {"Jupiter in Leo. Raise the torch high… and beware the wind that follows praise."},
        upright_keywords = {"victory", "recognition", "success", "leadership", "triumph", "spotlight", "rising above"},
        reversed_keywords = {"fall from grace", "self-doubt", "lack of recognition", "hollow victory", "pride before the fall", "obscurity"},
        upright_fortune = {
            "The banner waves. But fame is just a louder kind of ghost.",
            "Success lands. It's wearing sequins and demanding praise. Indulge it.",
            "You rode in triumph. The universe handed you flowers. Weird ones."
        },
        reversed_fortune = {
            "Victory was late. Now it's sulking and covered in glitter glue.",
            "Praise fades. Were you doing it for them… or for the mirror?",
            "You climbed the stage, tripped on your own ego. The spirits clapped anyway."
        },
    },
    ["Seven of Wands"] = {
        correspondence = {"Mars in Leo. The last light at the gate. One flame, surrounded, refuses to flicker."},
        upright_keywords = {"defense", "perseverance", "standing ground", "resilience", "challenge met", "holding the line"},
        reversed_keywords = {"overwhelmed", "giving up", "lack of defense", "insecurity", "surrender", "burnout", "unsupported stance"},
        upright_fortune = {
            "Challenge accepted. And by 'accepted' we mean aggressively headbutted.",
            "The hill is yours. Now defend it like a dramatic forest goblin.",
            "You stand alone. The odds laugh. You raise your wand anyway."
        },
        reversed_fortune = {
            "Overrun? Or just overwhelmed by how many wands aren't yours?",
            "Backed into a corner, which is just another kind of stage. Perform wisely.",
            "You dropped the stance. The universe raised its brow."
        },
    },
    ["Eight of Wands"] = {
        correspondence = {"Mercury in Sagittarius. Messages in the firelight... arrows of intent, swifter than thought."},
        upright_keywords = {"swift movement", "momentum", "communication", "rapid progress", "alignment", "green light"},
        reversed_keywords = {"delays", "miscommunication", "scattered focus", "chaos", "interruption", "stuck energy", "crossed signals"},
        upright_fortune = {
            "The message flies. Whether you catch it or not is your business.",
            "The sky is full of signs. Also flaming sticks. Duck wisely.",
            "Momentum builds. Spirit whispers: 'No brakes now, darling.'"
        },
        reversed_fortune = {
            "You threw the wand. It hit a tree. That's the omen.",
            "You tried to send a sign. The wind sent it back with edits.",
            "Divine buffering… please wait. The gods are recalculating."
        },
    },
    ["Nine of Wands"] = {
        correspondence = {"Moon in Sagittarius. Battered wood, scorched earth. But the flame still stands."},
        upright_keywords = {"resilience", "last stand", "perseverance", "guardedness", "battle-worn", "persistence", "near completion"},
        reversed_keywords = {"defeat", "paranoia", "giving up", "wounded pride", "unnecessary barriers", "hypervigilance", "collapse"},
        upright_fortune = {
            "You built these walls with your own scars. Cozy, right?",
            "Wounded? Yes. Defeated? Not in this timeline.",
            "You've been through it. Still standing. The spirits respect."
        },
        reversed_fortune = {
            "Defenses too high. Even blessings can't get in.",
            "Burnout disguised as bravery. The flame wants a nap.",
            "You dropped your guard. The chaos noticed."
        },
    },
    ["Ten of Wands"] = {
        correspondence = {"Saturn in Sagittarius. Even fire may falter when burdened. Release what smothers the spark."},
        upright_keywords = {"burden", "responsibility", "stress", "hard work", "overwhelm", "obligation", "weight of success"},
        reversed_keywords = {"release", "avoidance", "burnout", "letting go", "misplaced priorities", "unsustainable pressure", "collapse"},
        upright_fortune = {
            "Carrying too much? The universe offers a shrug… and one more wand.",
            "The load grows, but so does your weird pride in dragging it.",
            "Responsibility weighs you down. But hey, your calves look great."
        },
        reversed_fortune = {
            "The burden released. Now comes the awkward feeling of freedom.",
            "You offloaded everything. Except guilt. Classic move.",
            "You finally dropped the load. Was any of it even yours?"
        },
    },
    ["Page of Wands"] = {
        correspondence = {"Earth of Fire. The spark grins, curious and wild. Unaware it might soon become a wildfire."},
        upright_keywords = {"curiosity", "spark of adventure", "inspiration", "enthusiasm", "creative messenger", "playful energy"},
        reversed_keywords = {"scattered energy", "immaturity", "false start", "lack of direction", "unfinished ideas", "fleeting spark"},
        upright_fortune = {
            "You leap first, then ask 'Was that a cliff?'",
            "A message comes in flames. You reply with matches.",
            "A new idea strikes. You follow it... possibly into a cactus."
        },
        reversed_fortune = {
            "A spark fizzles. You blame the wind, but it's clearly your damp socks.",
            "The message misfires. The smoke signal spelled “oops.”",
            "You had a plan... it wandered off chasing butterflies."
        },
    },
    ["Knight of Wands"] = {
        correspondence = {"Fire of Fire. He rides with flame in his veins, no map, no brakes. Glory… or ash."},
        upright_keywords = {"passion", "bold action", "pursuit", "adventure", "risk-taking", "charisma", "momentum", "untamed fire"},
        reversed_keywords = {"recklessness", "arrogance", "impulsiveness", "broken promises", "burnout", "misdirected energy"},
        upright_fortune = {
            "The flame dances where you step, others follow the smoke, unsure if it leads or warns.",
            "Fire in your wake, embers in your eyes. The stars wonder if you're a force or a fluke.",
            "A spark rides the wind, laughing at the horizon. It trusts the air more than it should."
        },
        reversed_fortune = {
            "Arrogance wears a crown of sparks, blind to the wind that fuels its temporary blaze.",
            "The fire claims its own, leaving only the scent of burnt promises and fading trails.",
            "Reckless hearts leave scorched earth, but even fire weeps when it forgets how to burn."
        },
    },
    ["Queen of Wands"] = {
        correspondence = {"Water of Fire. She commands without asking. Fire wraps around her, not the other way."},
        upright_keywords = {"confidence", "magnetism", "independence", "inner power", "warmth", "creative authority", "fiery grace"},
        reversed_keywords = {"jealousy", "insecurity", "manipulation", "shadow charisma", "controlling nature", "scattered focus"},
        upright_fortune = {
            "The throne is yours. The fire just wonders if you'll stop to breathe before ruling the world.",
            "Confidence drips from your crown. Pity the shadows that dare cast doubt.",
            "You command the blaze, but even embers know when to flee your glare."
        },
        reversed_fortune = {
            "Vanity's mirror cracks. Reflects a queen who forgets the flame needs fuel, not just flair.",
            "Passion's queen? More like prisoner. Even the sun sets, darling; drama's exhausting.",
            "The crown tilts. The spirits laughs, whispering who really wears the crown tonight."
        },
    },
    ["King of Wands"] = {
        correspondence = {"Air of Fire. The flame speaks in strategy now. Not every fire is loud, some rule in silence."},
        upright_keywords = {"leadership", "vision", "strategic fire", "command", "ambition", "inspiration", "wise authority"},
        reversed_keywords = {"tyranny", "impulsive rule", "arrogance", "inflated ego", "intolerance", "abuse of power", "lost direction"},
        upright_fortune = {
            "The throne glows. Did you earn it, or just outshine the peasants?",
            "Vision burns bright. Pity the moths. They never learn.",
            "Majesty with a smirk. The sun's ego is legendary. And it's taking notes."
        },
        reversed_fortune = {
            "Authority flails. The kingdom's betting on how long the charade lasts. Place your coins.",
            "Charisma fades. The stars just rolled their eyes into another dimension.",
            "King of nothing but embers. Even the ash is packing its bags. Cue the violin."
        },
    },
}

