-- This file is AUTOMATICALLY GENERATED by generate_card_data.py
-- DO NOT EDIT THIS FILE MANUALLY!

CARD_DATA_CUPS = {
    ["Ace of Cups"] = {
        correspondence = {"The first drop falls. Love in its purest form, unclaimed and overflowing."},
        upright_keywords = {"love", "new feelings", "emotional beginnings", "intuition", "compassion", "spiritual flow", "heart opening"},
        reversed_keywords = {"emotional block", "emptiness", "repressed feelings", "creative drain", "heartbreak", "vulnerability", "spiritual disconnect", "withheld affection"},
        upright_fortune = {
            "The cup overflows. The heart whispers, 'Try not to drown in this.'",
            "A chalice unclaimed... ask the moon why it's suddenly sweating.",
            "Intuition hums. The well asks, 'Who let the dam crack?'"
        },
        reversed_fortune = {
            "The cup trembles. The heart hides behind a locked door. Again.",
            "Repression swirls. This cup dares you to pretend it's not half-empty.",
            "The soul knocks, but you're busy rearranging the 'Do Not Disturb' sign."
        },
    },
    ["Two of Cups"] = {
        correspondence = {"Venus in Cancer. A glance, a pact, a mirrored heart. Emotion recognizes itself and dares to connect."},
        upright_keywords = {"partnership", "attraction", "harmony", "union", "connection", "shared emotions"},
        reversed_keywords = {"imbalance", "disharmony", "breakup", "misunderstanding", "unrequited love", "misalignment"},
        upright_fortune = {
            "A pact sealed in spit and stardust. The moon winks; Try not to ruin it.",
            "Hearts sync. The stars roll their eyes but toss confetti anyway.",
            "Souls clink like glasses. 'To us' whispers the universe... Maybe."
        },
        reversed_fortune = {
            "The pact frays. The spirits tally bets on who blinks first. Spoiler: You.",
            "Mirrors crack. The tides retreat. Sorry, love. No refunds.",
            "The duet mutes. One heart shouts, the other hums a different tune."
        },
    },
    ["Three of Cups"] = {
        correspondence = {"Mercury in Cancer. The cup is shared. Voices rise in harmony, clinking joy that echoes beyond the veil."},
        upright_keywords = {"celebration", "friendship", "joy", "reunion", "community", "emotional support"},
        reversed_keywords = {"overindulgence", "gossip", "isolation", "third parties", "emotional burnout", "exclusion"},
        upright_fortune = {
            "Memories sweeten. The future leans in: 'Can I crash the party? I brought regrets.'",
            "Laughter braids the tides. This'll end in tears… later.",
            "A circle unbroken. A cosmic toast. To chaos, cheap wine, and borrowed time."
        },
        reversed_fortune = {
            "Honeyed venom drips. Feast's ghost lingers. Pass the salt… and the gossip.",
            "Echoes sour. The stars tap out. Your choir's off-key and overdressed.",
            "Cups tilt. The void sips again. Same vintage, still bitter."
        },
    },
    ["Four of Cups"] = {
        correspondence = {"Moon in Cancer. Still waters grow stagnant. The hand offers again… but the heart is elsewhere."},
        upright_keywords = {"apathy", "contemplation", "reevaluation", "disconnection", "introspection", "emotional detachment"},
        reversed_keywords = {"new outlook", "acceptance", "emotional renewal", "reengagement", "openness", "motivation"},
        upright_fortune = {
            "Reflection? No, the cup's too busy admiring its own cracks.",
            "The heart naps. Emotions queue politely… then leave a note: 'Back never.'",
            "Apathy pools. The tides file for divorce. Irreconcilable differences, I guess."
        },
        reversed_fortune = {
            "The chalice tilts… finally spilling the tea the soul refused to sip.",
            "The roots find water, reluctantly. Your heart grumbles and bloom.",
            "The tide turns… but the shore forgets to celebrate. Again."
        },
    },
    ["Five of Cups"] = {
        correspondence = {"Mars in Scorpio. Three spill. Two remain. Grief's fog hides what hope still floats."},
        upright_keywords = {"regret", "grief", "loss", "disappointment", "sorrow", "emotional focus"},
        reversed_keywords = {"acceptance", "healing", "forgiveness", "moving on", "perspective shift", "renewal"},
        upright_fortune = {
            "Three rivers lost to sand. A storm snickers. Did you really think you'd hold them all?",
            "Loss tallies. The mirror cracks. You're collecting regrets like seashells. Cute.",
            "The heart counts cracks. Mars grins. Drama's your best work, isn't it?"
        },
        reversed_fortune = {
            "The storm retches. Can you find pearls where the wreckage washed ashore?",
            "Mars shrugs, your heart agrees. Grief's a hobby. Time to pick a new one.",
            "The roots map new rivers. The cup will be half full again."
        },
    },
    ["Six of Cups"] = {
        correspondence = {"Sun in Scorpio. Memory sweetens the cup. But nostalgia brews both comfort and illusion."},
        upright_keywords = {"nostalgia", "childhood", "memories", "innocence", "comfort", "emotional roots"},
        reversed_keywords = {"living in the past", "clinging", "unrealistic ideals", "emotional stagnation", "unresolved issues", "sentimentality"},
        upright_fortune = {
            "Memories sweeten, but don't overindulge, darling.",
            "Childhood whispers secrets, listen very closely.",
            "Nostalgia's bitter comfort food, savor in moderation."
        },
        reversed_fortune = {
            "Don't drown in yesterday's regrets, sweetie, swim forward.",
            "Past is prologue, not a prescription, write your own story.",
            "Stagnant emotions equal stagnant life, stir the waters."
        },
    },
    ["Seven of Cups"] = {
        correspondence = {"Venus in Scorpio. The dream offers seven doors. Choose wrong, and drown in the mirage."},
        upright_keywords = {"choices", "illusions", "dreams", "temptation", "fantasy", "imagination"},
        reversed_keywords = {"clarity", "decision", "groundedness", "reality check", "narrowed focus", "disillusionment"},
        upright_fortune = {
            "Temptation is a siren, but you're not a ship, you're a sailor.",
            "Fantasy is fun, but don't forget to pay your rent in reality.",
            "Seven doors, seven dramas, choose wisely... if you can"
        },
        reversed_fortune = {
            "You chose the door with glitter, now you're lost in sparkle.",
            "Clarity arrives, and it's not as exciting as the illusion, sorry.",
            "Narrowed focus: you finally chose a door, now don't get distracted by the cat videos."
        },
    },
    ["Eight of Cups"] = {
        correspondence = {"Saturn in Pisces. The wine has soured. You walk away: not from love, but from its ghost."},
        upright_keywords = {"departure", "emotional withdrawal", "searching", "letting go", "inner journey", "dissatisfaction"},
        reversed_keywords = {"fear of change", "stagnation", "avoidance", "stuck emotions", "clinging", "aimlessness"},
        upright_fortune = {
            "The search begins, and the first clue is hidden in your heart.",
            "Letting go is not losing, it's just rearranging your emotional furniture.",
            "Time to walk the solo path, where the only ghost is your own."
        },
        reversed_fortune = {
            "Stagnation is a pond, and you're the fish who's forgotten how to swim.",
            "You're clinging to what's left, but it's just a handful of dust.",
            "Fear of change is just a fancy way of saying stuck in the mud."
        },
    },
    ["Nine of Cups"] = {
        correspondence = {"Jupiter in Pisces. The wish granted. The heart swells. But beware the fullness that forgets the soul."},
        upright_keywords = {"contentment", "satisfaction", "emotional fulfillment", "pleasure", "wish granted", "gratitude"},
        reversed_keywords = {"smugness", "disappointment", "indulgence", "unmet desires", "superficial joy", "hollow success"},
        upright_fortune = {
            "Your cup runneth over, but don't spill it on your shoes. You'll just have to clean up the mess.",
            "You've got the pleasure, now don't forget the purpose. Don't be a one-hit wonder.",
            "The cosmos grants your wish. Now don't get too comfortable, or you'll forget your own name."
        },
        reversed_fortune = {
            "You're so full of yourself, you've forgotten what you were wishing for. Oops.",
            "Smugness is not a spiritual practice, darling.",
            "Indulgence is not fulfillment. Don't confuse the two, or you'll end up with a tummy ache."
        },
    },
    ["Ten of Cups"] = {
        correspondence = {"Mars in Pisces. The storm has passed. The rainbow arches. Harmony, for a heartbeat or a lifetime."},
        upright_keywords = {"harmony", "emotional completion", "family", "joy", "lasting happiness", "shared dreams"},
        reversed_keywords = {"disharmony", "broken connection", "false happiness", "misaligned values", "tension", "emotional instability"},
        upright_fortune = {
            "Family is everything, unless you're a cat, then it's all about the solo nap time.",
            "Joy is contagious, but so is drama. Choose your tribe wisely.",
            "Harmony is a beautiful thing, but don't forget to appreciate the discordant notes that make the melody interesting."
        },
        reversed_fortune = {
            "Emotional instability is like a rollercoaster: thrilling, but also nauseating. Buckle up!",
            "False happiness or too much candy? Well, after the buzz, you'll crash and burn.",
            "Misaligned values are like shoes that don't fit: you'll trip and stumble, until you find your sole-mate."
        },
    },
    ["Page of Cups"] = {
        correspondence = {"Earth of Water. A fish speaks in riddles. You listen, heart open, logic... conveniently drowned."},
        upright_keywords = {"innocence", "emotional curiosity", "messages", "intuition", "creative beginnings", "sensitivity"},
        reversed_keywords = {"emotional immaturity", "creative block", "insecurity", "moodiness", "unrealistic hopes", "avoidance"},
        upright_fortune = {
            "Creative beginnings are like a mermaid's kiss: magical, but also slippery. Hold on tight, and see where the tide takes you.",
            "The universe is texting like your crush: cryptic, but worth decoding",
            "Dolphins whispers secrets, listen with a heart full of wonder. Just don't forget to bring a towel."
        },
        reversed_fortune = {
            "Are you feeling like a fish out of water? Flailing, making a big splash, but not really getting anywhere.",
            "The tides of moodiness will ebb and flow, bring your board and surf those waves.",
            "A message in a bottle won't get you off the island. Get a map, and a compass, and a sense of humor."
        },
    },
    ["Knight of Cups"] = {
        correspondence = {"Air of Water. He rides dreams like waves. A poet's promise, always just out of reach."},
        upright_keywords = {"romantic offer", "charm", "idealism", "pursuit of dreams", "emotional quest", "imagination"},
        reversed_keywords = {"manipulation", "mood swings", "jealousy", "unrealistic fantasy", "emotional volatility", "seduction"},
        upright_fortune = {
            "A romantic offer arrives, borne on the wings of poetry and promise. Words are sweet, but actions are the chocolate factory.",
            "The pursuit of dreams is a noble quest, but don't forget the long and winding road leading to the door.",
            "Idealism is a guiding star, that you'll follow to the ends of the earth. Or at least, until the next shiny thing appears."
        },
        reversed_fortune = {
            "The fantasy is a tempting trap, but it's just that. Don't get caught in the web of your own desires.",
            "Jealousy is a dark and twisted thing, and it can consume even the most beautiful of souls. And by that I mean me.",
            "Emotional volatility is a stormy sea. Find your Nemo and hold tight"
        },
    },
    ["Queen of Cups"] = {
        correspondence = {"Water of Water. She listens deeper than words. Her gaze stirs tides. Nothing is truly hidden."},
        upright_keywords = {"empathy", "compassion", "intuition", "emotional depth", "nurturing", "inner calm"},
        reversed_keywords = {"emotional overwhelm", "codependency", "suppression", "insecurity", "hypersensitivity", "escapism"},
        upright_fortune = {
            "Congratulations, you're now officially an emotional genius. Use your powers for good, not for obsessing over your ex.",
            "Remember, self-care is not just a hashtag, it's a necessity. Take care of your heart, or it'll take care of you.",
            "The depths of your feelings are a mess, but hey, at least you're consistent. Dive in, and try to untangle the drama."
        },
        reversed_fortune = {
            "Your emotions are a hot mess, but don't worry, it's not like you're alone or anything. Just kidding, you're totally alone in this mess.",
            "Your emotional storm is not a metaphor, it's a real thing. Take cover, and try not to get too wet.",
            "Codependency is not a relationship goal. It's more like a cry for help. Will the spirits guide you out?"
        },
    },
    ["King of Cups"] = {
        correspondence = {"Fire of Water. The sea rages. He does not. Emotion held like wine: potent, poised, and masked."},
        upright_keywords = {"emotional balance", "wisdom", "diplomacy", "compassion", "control", "maturity"},
        reversed_keywords = {"emotional repression", "manipulation", "coldness", "instability", "passive-aggression", "detachment"},
        upright_fortune = {
            "Wisdom is not just about knowing things, it's about knowing when to keep your mouth shut.",
            "Compassion is not just a feeling, it's a superpower. Use it to heal, not to enable, sweetie.",
            "Diplomacy is the art of saying yes without meaning it. Yes?"
        },
        reversed_fortune = {
            "Coldness is not the same as calmness. One is a frozen lake, the other is a peaceful ocean. Brrrrr.",
            "The rollercoaster of instability it's fun for a while, but eventually, you'll want to get off and vomit.",
            "Are you repressing emotions or holding your breath underwater? Be carefull, eventually you'll turn blue and float to the surface."
        },
    },
}

