-- This file is AUTOMATICALLY GENERATED by generate_card_data.py
-- DO NOT EDIT THIS FILE MANUALLY!

CARD_DATA_PENTACLES = {
    ["Ace of Pentacles"] = {
        correspondence = {"The first seed rests in hand. Potential hums, slow, golden, and hungry to root."},
        upright_keywords = {"new opportunity", "prosperity", "grounded beginnings", "manifestation", "abundance", "seed planted"},
        reversed_keywords = {"missed chance", "instability", "poor planning", "delay", "false start", "blocked potential"},
        upright_fortune = {
            "The universe just handed you a seed. Try not to plant it in cement.",
            "A fresh start, grounded in… well, ground. Have fun.",
            "A new opportunity lands. Don't trip over it."
        },
        reversed_fortune = {
            "Potential, meet procrastination. You two should get along.",
            "A false start. At least you got a start, right?",
            "Plans are lovely. When they're actually made."
        },
    },
    ["Two of Pentacles"] = {
        correspondence = {"Jupiter in Capricorn. The dance of matter and motion. Coins spin, time sways. Balance or blur?"},
        upright_keywords = {"balance", "adaptability", "juggling priorities", "time management", "flow", "organized chaos"},
        reversed_keywords = {"imbalance", "overwhelm", "dropped ball", "poor budgeting", "chaos", "burnout"},
        upright_fortune = {
            "Adapt or collapse. The cosmos has a sense of humor.",
            "Juggling coins is easy. Juggling your life? That's the real circus.",
            "Your priorities are dancing. Try to keep them from stepping on each other."
        },
        reversed_fortune = {
            "Dropped ball. Or perhaps, dropped everything.",
            "Imbalance achieved! Did you even try?",
            "Chaos reigns. Your budget just wept."
        },
    },
    ["Three of Pentacles"] = {
        correspondence = {"Mars in Capricorn. Stone meets vision. The craft demands hands, hearts, and humble plans."},
        upright_keywords = {"collaboration", "teamwork", "craftsmanship", "skill building", "shared vision", "steady progress"},
        reversed_keywords = {"lack of harmony", "poor workmanship", "ego clash", "disorganization", "misalignment", "no support"},
        upright_fortune = {
            "Your vision aligns. Hopefully with reality.",
            "Teamwork makes the dream work. Mostly for the team.",
            "Skills honed. The stars applauds your effort, minimally."
        },
        reversed_fortune = {
            "Misalignment. You're building a tower, but on a swamp.",
            "Harmony left. Probably because of your ego.",
            "Poor workmanship. Even the spirits are tutting."
        },
    },
    ["Four of Pentacles"] = {
        correspondence = {"Sun in Capricorn. You clutch the coin. It clutches back. Security or stagnation? Hard to tell."},
        upright_keywords = {"control", "saving", "boundaries", "security", "holding tight", "protecting assets"},
        reversed_keywords = {"greed", "release", "fear of loss", "scarcity mindset", "financial instability", "letting go"},
        upright_fortune = {
            "Saving pennies. While the universe offers fortunes. Okay, Scrooge.",
            "You're clutching that coin. Is it security, or just paralysis?",
            "Control is lovely. Until it controls you."
        },
        reversed_fortune = {
            "Release! Or be dragged down. Your choice, darling.",
            "Scarcity mindset. When the universe is overflowing. How quaint.",
            "Fear of loss. Which, ironically, invites loss."
        },
    },
    ["Five of Pentacles"] = {
        correspondence = {"Mercury in Taurus. Doors shut. Cold bites. But between silence and snow… a light flickers."},
        upright_keywords = {"hardship", "poverty", "isolation", "spiritual drought", "abandonment", "survival mode"},
        reversed_keywords = {"recovery", "help offered", "hope renewed", "light returning", "rebuilding", "spiritual refuge"},
        upright_fortune = {
            "Survival mode engaged. Good luck, you'll need it.",
            "Spiritual drought. Are you sure you checked under the couch?",
            "Hardship arrives. At least it's authentic."
        },
        reversed_fortune = {
            "Rebuilding. From the ashes. Very dramatic.",
            "Hope renewed. It's a small spark, but at least it's something.",
            "If help is offered, try not to squint suspiciously at it."
        },
    },
    ["Six of Pentacles"] = {
        correspondence = {"Moon in Taurus. The hand gives. The hand receives. And both are tested by the weight of gold."},
        upright_keywords = {"generosity", "giving and receiving", "support", "charity", "balance restored", "mutual aid"},
        reversed_keywords = {"strings attached", "debt", "power imbalance", "greed", "withheld support", "unequal exchange"},
        upright_fortune = {
            "The hand gives, the hand receives. Cosmic karma, or just good accounting?",
            "Balance restored. Wobble, the scales of fate, no longer do.",
            "Support arrives. As a hail mary pass."
        },
        reversed_fortune = {
            "Alright puppet master. Your generosity came with a receipt.",
            "Check your balance. The universe remembers everything.",
            "Imbalance of power, this is. Like a Sith Lord, one grows, while the other withers."
        },
    },
    ["Seven of Pentacles"] = {
        correspondence = {"Saturn in Taurus. The soil waits. So do you. Patience blooms in the quiet between efforts."},
        upright_keywords = {"patience", "long-term vision", "slow growth", "investment", "assessment", "harvest pending"},
        reversed_keywords = {"impatience", "wasted effort", "short-term thinking", "frustration", "poor return", "neglect"},
        upright_fortune = {
            "Your growth like watching paint dry, but with more potential.",
            "Invest!. Now, just wait. And wait... And wait.",
            "Harvest loading... Don't hold your breath."
        },
        reversed_fortune = {
            "Don't like what you got? Next time, read the fine print.",
            "Frustration levels rising. The cosmos is unconcerned.",
            "If you look ahead you'll see your future self is judging you."
        },
    },
    ["Eight of Pentacles"] = {
        correspondence = {"Sun in Virgo. The rhythm of work. Etch, shape, repeat. Mastery hums beneath the mundane."},
        upright_keywords = {"craftsmanship", "dedication", "skill development", "hard work", "mastery", "apprenticeship"},
        reversed_keywords = {"burnout", "sloppy work", "lack of focus", "cutting corners", "stagnation", "disinterest"},
        upright_fortune = {
            "The slow grind. It's less glamorous than a cheat code.",
            "Learning the hard way, as usual.",
            "Mastery in the making. Just keep sanding."
        },
        reversed_fortune = {
            "Your mind is a squirrel on caffeine. Focus.",
            "Can you smell the burnout? Told you to take a break.",
            "Cutting corners. The universe notices. Eventually..."
        },
    },
    ["Nine of Pentacles"] = {
        correspondence = {"Venus in Virgo. Solitude in silk. What's earned whispers sweeter than what's given."},
        upright_keywords = {"self-sufficiency", "luxury", "independence", "refinement", "comfort", "earned success"},
        reversed_keywords = {"overdependence", "superficial wealth", "isolation", "financial setbacks", "insecurity", "loss of freedom"},
        upright_fortune = {
            "Right, you derserve it! Now, try not to brag too much.",
            "Indepence communes with the cosmos. It prefers solitude.",
            "Look at that refinement. Lush! Your inner snob approves."
        },
        reversed_fortune = {
            "Are you sure you can't tie your own shoes?",
            "Isolation sets in. You pushed everyone away, remember?",
            "All that glitters is gold. It's shiny, but hollow."
        },
    },
    ["Ten of Pentacles"] = {
        correspondence = {"Mercury in Virgo. Legacy is layered. Coins and bones, names and echoes. What endures, endures well."},
        upright_keywords = {"legacy", "long-term success", "family wealth", "inheritance", "roots", "stability"},
        reversed_keywords = {"instability", "broken traditions", "financial loss", "family tension", "short-sightedness", "collapse"},
        upright_fortune = {
            "Ah, what a legacy! Coins and bones, quite the collection.",
            "Roots run deep. Hopefully not into quicksand.",
            "The awaited long-term success. It only took forever."
        },
        reversed_fortune = {
            "Instability reigns. Your foundations are crumbling.",
            "Family dinner? Pass the awkward silence please.",
            "The universe giveth... and then taketh."
        },
    },
    ["Page of Pentacles"] = {
        correspondence = {"Earth of Earth. The apprentice dreams of gold. Not for greed, but for the alchemy of becoming."},
        upright_keywords = {"new goals", "grounded curiosity", "student mindset", "planning", "opportunity", "fresh ideas"},
        reversed_keywords = {"procrastination", "lack of commitment", "daydreaming", "missed chances", "scattered effort", "immaturity"},
        upright_fortune = {
            "A new goal sprouts. Nurture it, or watch it wither. Your call.",
            "The apprentice dreams of gold. May your alchemy be true.",
            "Opportunity knocks. Don't mistake it for a bill collector."
        },
        reversed_fortune = {
            "Procrastination's heavy cloak. That opportunity? It just walked past you.",
            "Daydreams persist. Reality, however, requires a bit more effort.",
            "Scattered efforts, like spilled coins. None land where they matter."
        },
    },
    ["Knight of Pentacles"] = {
        correspondence = {"Air of Earth. The plow moves slow, but never strays. Duty etched in every careful step."},
        upright_keywords = {"responsibility", "routine", "loyalty", "steady progress", "hard-earned results", "diligence"},
        reversed_keywords = {"laziness", "stubbornness", "stuckness", "risk aversion", "boredom", "missed momentum"},
        upright_fortune = {
            "Diligence personified. Even the stars appreciate a good work ethic.",
            "Steady progress. It's not a race, darling, it's a marathon.",
            "The plow moves slow, but never strays. Duty is your unwavering guide."
        },
        reversed_fortune = {
            "Laziness reigns. The universe finds your lack of effort… predictable.",
            "Risk aversion, or just fear? You decide. The cosmos already has.",
            "Boredom's dull hum. Perhaps a new path is less… horizontal?"
        },
    },
    ["Queen of Pentacles"] = {
        correspondence = {"Water of Earth. She nurtures in stillness. Her abundance is not loud, but everything grows near her."},
        upright_keywords = {"nurturing", "abundance", "practical care", "resourcefulness", "fertility", "financial wisdom"},
        reversed_keywords = {"smothering", "imbalance", "materialism", "overextension", "self-neglect", "disconnection"},
        upright_fortune = {
            "Her fertility blesses the earth. And, occasionally, your bank account.",
            "Practical care offered. No fanfare, just steady support.",
            "Abundance blooms quietly. Its roots run deep, unseen."
        },
        reversed_fortune = {
            "Elmyra Duff's love language. Careful, too much love can indeed kill.",
            "You can't pour from an empty cup, no matter how shiny.",
            "Disconnection from the earthly plane. Get grounded, sweetie."
        },
    },
    ["King of Pentacles"] = {
        correspondence = {"Fire of Earth. He builds, protects, and remembers. His throne is carved from patience and promise."},
        upright_keywords = {"prosperity", "mastery", "stability", "leadership", "wealth", "grounded power"},
        reversed_keywords = {"greed", "control issues", "corruption", "insecurity masked by wealth", "rigidity", "fear of failure"},
        upright_fortune = {
            "Wealth's true measure. It's not just coins, it's enduring power.",
            "A chessmaster leader. He is thousands moves ahead, always.",
            "Toph is proud! Even the mountains take notes of your stability."
        },
        reversed_fortune = {
            "Why bend when you can just break everything around you?",
            "You're starring in a one puppet show as the only marionette who doesn't realize they got strings.",
            "Corrupt? Just optimizing the system. Exclusively for yourself of course."
        },
    },
}

