-- This file is AUTOMATICALLY GENERATED by generate_card_data.py
-- DO NOT EDIT THIS FILE MANUALLY!

CARD_DATA_MAJOR = {
    ["The Fool"] = {
        correspondence = {"Of Air, yet untethered by any sign... Uranus governs its wild path."},
        upright_keywords = {"new beginnings", "innocence", "spontaneity", "adventure", "faith", "freedom", "potential"},
        reversed_keywords = {"recklessness", "naivety", "holding back", "fear of the unknown", "foolishness"},
        upright_fortune = {
            "The wind calls. You follow. Spirit guides sigh. But destiny adores the bold.",
            "The veil parts. You rush in. Spirits mutter: Here we go again.",
            "New paths open. You didn't pack wisdom, but the stars enjoy a good show."
        },
        reversed_fortune = {
            "You hesitate at the edge. The universe shrugs and keeps moving.",
            "The signs were clear. You brought sunglasses. Bold.",
            "A stumble before the first step. Cards are watching, mildly entertained."
        },
    },
    ["The Magician"] = {
        correspondence = {"Air-born and ruled by Mercury, master of words and will."},
        upright_keywords = {"manifestation", "resourcefulness", "power", "inspired action", "skills", "will"},
        reversed_keywords = {"manipulation", "deception", "lost essence", "dormant force", "trickery"},
        upright_fortune = {
            "All tools are here. Whether you know how to use them... well, that's the real trick.",
            "The stars align. You claim the credit. Classic Magician move.",
            "As above, so below. As within… still loading."
        },
        reversed_fortune = {
            "The trick was good. Until you forgot what you were conjuring.",
            "Power misused? Or unused? Either way, something smells of ego and incense.",
            "The illusion fails. The curtain falls. The silence is… educational."
        },
    },
    ["The High Priestess"] = {
        correspondence = {"Flowing with the tides of Water her spirit dances with the Moon."},
        upright_keywords = {"intuition", "mystery", "inner voice", "subconscious mind", "wisdom", "silence"},
        reversed_keywords = {"secrets", "withdrawal", "blocked intuition", "disconnection", "hidden motives"},
        upright_fortune = {
            "Silence speaks. You ask again. She blinks slowly.",
            "Secrets rise like mist. You inhale. Now you're coughing on truth.",
            "The answers are within, but they'll probably just leave you on read."
        },
        reversed_fortune = {
            "You ghosted the signs. The signs did not appreciate that.",
            "Intuition denied. She crosses her arms. The moon turns away.",
            "Your inner voice whispered. You replied with a meme."
        },
    },
    ["The Empress"] = {
        correspondence = {"Rooted in Earth, and ruled with sensual grace by Venus."},
        upright_keywords = {"abundance", "nurturing", "fertility", "beauty", "nature", "creation", "motherhood"},
        reversed_keywords = {"smothering", "dependence", "creative block", "neglected self-care", "insecurity"},
        upright_fortune = {
            "She gives freely. Just don't ask where it came from or when it expires.",
            "Abundance flows. You say thanks. She's already moved on to pruning you.",
            "Nature nurtures. Unless you forget to water it. Then... well.."
        },
        reversed_fortune = {
            "You asked for growth. She gave silence. Maybe check the roots.",
            "Creation withheld. Even the soil rolls its eyes.",
            "Neglect wears perfume. The smell lingers and is not gucci."
        },
    },
    ["The Emperor"] = {
        correspondence = {"Forged in Fire, and commanded by the red planet Mars."},
        upright_keywords = {"authority", "structure", "stability", "leadership", "discipline", "power"},
        reversed_keywords = {"control issues", "tyranny", "rigidity", "chaos", "abuse of power", "stubbornness"},
        upright_fortune = {
            "Order reigns. You may now pretend it was your idea.",
            "Stability arrives. It's wearing boots and checking your work.",
            "You built the walls. Now enjoy the view from inside them."
        },
        reversed_fortune = {
            "A ruler without a plan. At least the crown fits.",
            "You clung to power. Power shrugged and left early.",
            "Authority questioned. You flinched. He didn't blink."
        },
    },
    ["The Hierophant"] = {
        correspondence = {"Solid Earth beneath him. Jupiter offers divine wisdom from above."},
        upright_keywords = {"tradition", "spiritual guidance", "education", "conformity", "institutions", "beliefs"},
        reversed_keywords = {"rebellion", "nonconformity", "false beliefs", "poor counsel", "challenge to tradition"},
        upright_fortune = {
            "Tradition calls. Or maybe it's just your Nana. Listen to one of them, at least.",
            "Seek wisdom from dusty books or wise elders. Both smell vaguely of mothballs.",
            "A teacher appears. Try to look like you're actually paying close attention."
        },
        reversed_fortune = {
            "Forget the old ways. Make new mistakes. It's more fun, trust me on this.",
            "Dogma got you down? Perhaps it's time to invent your own confusing rules.",
            "You're challenging the status quo. The status quo is mildly annoyed by this."
        },
    },
    ["The Lovers"] = {
        correspondence = {"Air moves between two. Mercury guides their choice, under Gemini's twin gaze."},
        upright_keywords = {"choices", "connection", "harmony", "union", "alignment", "values"},
        reversed_keywords = {"imbalance", "misalignment", "indecision", "disharmony", "breakup", "conflict"},
        upright_fortune = {
            "Important decisions loom. The universe is watching. And probably taking notes.",
            "Crossroads of the heart. May your intuition GPS be vaguely accurate.",
            "Values aligning, hearts connecting. Or perhaps you just share the same Wi-Fi."
        },
        reversed_fortune = {
            "Misalignment! Your heart says yes, your head says no, your gut just wants a snack.",
            "A choice regretted? Or perhaps a choice cleverly avoided. The jury is still out.",
            "That big decision? You've decided to decide later. A bold strategy, truly."
        },
    },
    ["The Chariot"] = {
        correspondence = {"The power of Water surges forward, driven beneath the banner of Cancer."},
        upright_keywords = {"willpower", "determination", "control", "triumph", "focus", "drive"},
        reversed_keywords = {"lack of direction", "aggression", "self-doubt", "scattered focus", "delays"},
        upright_fortune = {
            "Your quest fueled by drive, purpose, and a worrying amount of caffeine.",
            "Forward! Just make sure you're not charging confidently off a cliff.",
            "Ambition is your co pilot. Let's hope it knows how to read the celestial map."
        },
        reversed_fortune = {
            "Obstacles abound. Did you try turning it off and on again? The chariot, I mean.",
            "Control has slipped. The sphinxes are now taking you on a very scenic detour.",
            "Ambition stalled. Your chariot needs a spiritual oil change. Or snacks."
        },
    },
    ["Strength"] = {
        correspondence = {"Flames burn steady, this is Fire in the form of Leo's heart, ruled by the Sun."},
        upright_keywords = {"courage", "inner strength", "patience", "compassion", "resilience", "self-control"},
        reversed_keywords = {"insecurity", "self-doubt", "weakness", "lack of discipline", "emotional outburst"},
        upright_fortune = {
            "Control through kindness. The universe finds this approach... effective.",
            "Inner courage shines. You face the beast, or maybe just finally clean your room.",
            "Patience with the beast within. And the slightly annoying beast next door."
        },
        reversed_fortune = {
            "Self doubt whispers. Or shouts. Depends on how much sleep you've had, dear.",
            "Force isn't working. Perhaps it prefers a gentle scratch behind the ears.",
            "That inner lion? It's currently napping. And possibly drooling..."
        },
    },
    ["The Hermit"] = {
        correspondence = {"Earth-bound steps, yet the mind is Mercury's... silent under Virgo's stars."},
        upright_keywords = {"introspection", "solitude", "guidance", "inner truth", "wisdom", "spiritual journey"},
        reversed_keywords = {"isolation", "loneliness", "withdrawal", "fear of being alone", "avoidance"},
        upright_fortune = {
            "Introspection calls. Or maybe your Wi-Fi is down. Deep thoughts either way.",
            "Seeking wisdom within. Don't be alarmed if you only find old song lyrics.",
            "Withdrawing to reflect. Or hiding from responsibilities. Very spiritual."
        },
        reversed_fortune = {
            "Fear of the outside world. The squirrel in the garden seems a bit judgy, true.",
            "Emerging from solitude, blinking. Or just reluctantly rejoining society.",
            "Isolation becomes loneliness. Even your shadow is asking for some company now."
        },
    },
    ["Wheel of Fortune"] = {
        correspondence = {"Elemental alignments shift. Jupiter presides over its ever-turning fate."},
        upright_keywords = {"change", "cycles", "luck", "destiny", "karma", "opportunity"},
        reversed_keywords = {"bad luck", "resistance to change", "stagnation", "setbacks", "cycles repeating"},
        upright_fortune = {
            "What goes around... keeps going around. Hold on.",
            "Fate knocks. You open. It spins you anyway.",
            "Change arrives. Try not to act surprised this time."
        },
        reversed_fortune = {
            "The wheel jammed. You kicked it. Now it's offended.",
            "Bad luck? Or just bad timing. Either way, it's spinning again.",
            "You tried to stop fate. Fate laughed. Loudly."
        },
    },
    ["Justice"] = {
        correspondence = {"Air holds the scales. Venus whispers fairness through Libra's breath."},
        upright_keywords = {"fairness", "truth", "law", "balance", "accountability", "cause and effect"},
        reversed_keywords = {"injustice", "dishonesty", "unfairness", "imbalance", "corruption", "denial"},
        upright_fortune = {
            "The scales align. Hopefully you're not standing on the wrong side.",
            "Truth arrives. You might want to sit down first.",
            "Balance has the Force found. Easy, the path was not."
        },
        reversed_fortune = {
            "Justice delays. She's filing her nails and reviewing your mistakes.",
            "A truth ignored still waits. She has time. Do you?",
            "The scales tip. It wasn't in your favor. Or your control."
        },
    },
    ["The Hanged Man"] = {
        correspondence = {"Suspended in Water's mystery, under Neptune's slow and dreamlike pull."},
        upright_keywords = {"letting go", "new perspective", "pause", "surrender", "suspension", "insight"},
        reversed_keywords = {"stalling", "indecision", "resistance to change", "delay", "fear of sacrifice"},
        upright_fortune = {
            "Nothing moves. Yet everything rearranges behind your back.",
            "Stillness is loud. But only to those who truly listen.",
            "Suspended, you wait. Time forgets you. Insight remembers."
        },
        reversed_fortune = {
            "You resist the pause. The pause resists back.",
            "You hung there for meaning. Found mild dizziness instead.",
            "The view's the same. But now your foot's asleep."
        },
    },
    ["Death"] = {
        correspondence = {"Dark Water flows through this gate. Pluto rules from the depths of Scorpio."},
        upright_keywords = {"transformation", "endings", "change", "release", "renewal", "rebirth"},
        reversed_keywords = {"fear of change", "stagnation", "resistance", "decay", "clinging to the past"},
        upright_fortune = {
            "Transformation knocks. And no, it didn't bring a gift.",
            "The end arrives in velvet gloves. It's more polite than you'd think.",
            "Something ends. Cue eerie music. You know the drill."
        },
        reversed_fortune = {
            "You clung to the past. It rolled its eyes and left without you.",
            "You're not transforming. You're just dramatically resisting.",
            "The ending delayed. Now it's awkward for everyone."
        },
    },
    ["Temperance"] = {
        correspondence = {"Balanced by the rhythm of Fire, hallowed by Jupiter's hand in Sagittarius."},
        upright_keywords = {"balance", "moderation", "harmony", "healing", "purpose", "blending"},
        reversed_keywords = {"imbalance", "excess", "conflict", "lack of harmony", "impatience"},
        upright_fortune = {
            "You pour, you wait. The stars stir gently in response.",
            "Harmony hums. You don't need to sing along... just listen.",
            "Still waters mix. Slowly. Quietly. But never by accident."
        },
        reversed_fortune = {
            "You spilled the cup. Now the silence is disappointed.",
            "Too much of one thing. The cosmos frowns politely.",
            "The mix is off. It tastes like rushing."
        },
    },
    ["The Devil"] = {
        correspondence = {"Earth's shadow binds Saturn's cold dominion beneath Capricorn."},
        upright_keywords = {"temptation", "materialism", "bondage", "shadow self", "indulgence", "power plays"},
        reversed_keywords = {"release", "detachment", "breaking free", "reclaiming power", "awareness of toxicity"},
        upright_fortune = {
            "He offered you the deal. You brought your own pen.",
            "You're chained. But the lock? It's been fake this whole time.",
            "Temptation calls. You already answered. Twice."
        },
        reversed_fortune = {
            "Freedom's close. But drama is sooo much closer.",
            "You loosened the chains... then tied a prettier knot.",
            "The mask slips... Surprise! It was yours the whole time."
        },
    },
    ["The Tower"] = {
        correspondence = {"Fire consumes the false, Mars commands the strike."},
        upright_keywords = {"sudden change", "upheaval", "awakening", "revelation", "chaos", "breakthrough"},
        reversed_keywords = {"precaution", "stasis", "entrenchement", "false stability"},
        upright_fortune = {
            "You built it high. The fall was just part of the deal.",
            "The lightning struck. Now the truth can breathe.",
            "It falls. Not because it hated you, just because it had to."
        },
        reversed_fortune = {
            "You saw the signs. You smiled anyway. Brave.",
            "Avoided disaster? Or just stuck in the waiting room?",
            "The fall was postponed. But the view's still shaking."
        },
    },
    ["The Star"] = {
        correspondence = {"Air-born hope under Aquarius' sky, ruled by Uranus, awakener of souls."},
        upright_keywords = {"hope", "inspiration", "faith", "renewal", "peace", "spiritual clarity"},
        reversed_keywords = {"hopelessness", "discouragement", "distrust", "disconnect", "inertia"},
        upright_fortune = {
            "Hope lingers. Not loud, just stubborn.",
            "A light appears. You squint, then pretend you saw it first.",
            "The cosmos exhales. You may now stop spiraling."
        },
        reversed_fortune = {
            "You looked up… and still managed to trip over yourself.",
            "Wishing won't help if you keep watering weeds.",
            "The stars whispered. You answered with static."
        },
    },
    ["The Moon"] = {
        correspondence = {"Deep Water, deeper illusions. The Moon governs a nocturnal path in Pisces."},
        upright_keywords = {"illusion", "intuition", "confusion", "dreams", "subconscious", "the unknown"},
        reversed_keywords = {"unveiling", "releasing fear", "illumination", "awakening"},
        upright_fortune = {
            "You wander the mist. The path prefers it that way.",
            "Something stirs below. Pretend you didn't feel it.",
            "The Moon glows. You squint. And call it clarity."
        },
        reversed_fortune = {
            "Illusions fade. The truth looks slightly annoyed.",
            "You chased answers. The dream just changed the question.",
            "You see it now. Unfortunately, it sees you too."
        },
    },
    ["The Sun"] = {
        correspondence = {"Radiant Fire, unfiltered. Ruled by the Sun itself in Leo's endless blaze."},
        upright_keywords = {"joy", "success", "positivity", "vitality", "clarity", "growth"},
        reversed_keywords = {"brief sorrow", "stifled joy", "idealisation", "burnout"},
        upright_fortune = {
            "Everything blooms. Even your doubt looks confused.",
            "Truth tans well.\nYou, less so.",
            "The light hits. You pretend you weren't in the dark."
        },
        reversed_fortune = {
            "The joy fades. Maybe sunscreen wasn't your only mistake.",
            "Clouds pass. But you packed for sunshine only.",
            "Too much light? Careful... it shows everything."
        },
    },
    ["Judgement"] = {
        correspondence = {"Air rises with the call.\nPluto echoes the final note beyond Scorpio's veil."},
        upright_keywords = {"awakening", "reflection", "reckoning", "rebirth", "inner calling", "decision"},
        reversed_keywords = {"self-doubt", "poor judgment", "failure to learn", "ignoring a warning"},
        upright_fortune = {
            "Judgement is near. Do you hear the thunder or just the echoes of regret?",
            "The past whispers your name. Will you rise or stay buried in old mistakes?",
            "The final call comes. Answer before someone else picks it up."
        },
        reversed_fortune = {
            "Denial is your shield, but shadows grow longer. Truth will find you soon enough.",
            "You dodge the reckoning, but fate's patience wears thin with every lie.",
            "The chance to rise slips away when you close your ears to your own soul."
        },
    },
    ["The World"] = {
        correspondence = {"Earth's great completion, turned by Saturn's ancient ring."},
        upright_keywords = {"completion", "achievement", "wholeness", "fulfillment", "integration", "travel"},
        reversed_keywords = {"incompletion", "delays", "lack of closure", "stagnation", "loose ends"},
        upright_fortune = {
            "Full circle again. Did you learn something or just get dizzy?",
            "The world is yours, but it's also watching. Time to dance or awkwardly shuffle?",
            "Keep cranking the Playdate of fate; the world rewards those who don't quit."
        },
        reversed_fortune = {
            "You're almost there, but the universe says: Try again, buddy. I'm not done.",
            "The circle's broken, but hey, sometimes a jagged edge is more interesting.",
            "Close but no cigar. The world waits. You're busy daydreaming backstage."
        },
    },
}

