-- This file is AUTOMATICALLY GENERATED by generate_card_data.py
-- DO NOT EDIT THIS FILE MANUALLY!

CARD_DATA_CUPS = {
    ["Ace of Cups"] = {
        correspondence = {"The first drop falls. Love in its purest form, unclaimed and overflowing."},
        upright_keywords = {"love", "new feelings", "emotional beginnings", "intuition", "compassion", "spiritual flow", "heart opening"},
        reversed_keywords = {"emotional block", "emptiness", "repressed feelings", "creative drain", "heartbreak", "vulnerability", "spiritual disconnect", "withheld affection"},
        upright_fortune = {
            "The cup overflows. The heart whispers, 'Try not to drown in this.'",
            "A chalice unclaimed... ask the moon why it's suddenly sweating.",
            "Intuition hums. The well asks, 'Who let the dam crack?'"
        },
        reversed_fortune = {
            "The cup trembles. The heart hides behind a locked door. Again.",
            "Repression swirls. This cup dares you to pretend it's not half-empty.",
            "The soul knocks, but you're busy rearranging the 'Do Not Disturb' sign."
        },
    },
    ["Two of Cups"] = {
        correspondence = {"Venus in Cancer. A glance, a pact, a mirrored heart.", "Emotion recognizes itself and dares to connect."},
        upright_keywords = {"partnership", "attraction", "harmony", "union", "connection", "shared emotions"},
        reversed_keywords = {"imbalance", "disharmony", "breakup", "misunderstanding", "unrequited love", "misalignment"},
        upright_fortune = {
            "A pact sealed in spit and stardust. The moon winks; Try not to ruin it.",
            "Hearts sync. The stars roll their eyes but toss confetti anyway.",
            "Souls clink like glasses. 'To us' whispers the universe... Maybe."
        },
        reversed_fortune = {
            "The pact frays. The spirits tally bets on who blinks first. Spoiler: You.",
            "Mirrors crack. The tides retreat. Sorry, love. No refunds.",
            "The duet mutes. One heart shouts, the other hums a different tune."
        },
    },
    ["Three of Cups"] = {
        correspondence = {"Mercury in Cancer. The cup is shared.", "Voices rise in harmony, clinking joy that echoes beyond the veil."},
        upright_keywords = {"celebration", "friendship", "joy", "reunion", "community", "emotional support"},
        reversed_keywords = {"overindulgence", "gossip", "isolation", "third parties", "emotional burnout", "exclusion"},
        upright_fortune = {
            "Memories sweeten. Future leans: 'Can I crash the party? I brought regrets.'",
            "Laughter braids the tides. This'll end in tears… later.",
            "A circle unbroken. A cosmic toast. To chaos, cheap wine, and borrowed time."
        },
        reversed_fortune = {
            "Honeyed venom drips. Feast's ghost lingers. Pass the salt… and the gossip.",
            "Echoes sour. The stars tap out. Your choir's off-key and overdressed.",
            "Cups tilt. The void sips again. Same vintage, still bitter."
        },
    },
    ["Four of Cups"] = {
        correspondence = {"Moon in Cancer. Still waters grow stagnant.", "The hand offers again… but the heart is elsewhere."},
        upright_keywords = {"apathy", "contemplation", "reevaluation", "disconnection", "introspection", "emotional detachment"},
        reversed_keywords = {"new outlook", "acceptance", "emotional renewal", "reengagement", "openness", "motivation"},
        upright_fortune = {
            "Reflection? No, the cup's too busy admiring its own cracks.",
            "The heart naps. Emotions queue politely… then leave a note: 'Back never.'",
            "Apathy pools. The tides file for divorce. Irreconcilable differences, I guess."
        },
        reversed_fortune = {
            "The chalice tilts… finally spilling the tea the soul refused to sip.",
            "The roots find water, reluctantly. Your heart grumbles and bloom.",
            "The tide turns… but the shore forgets to celebrate. Again."
        },
    },
    ["Five of Cups"] = {
        correspondence = {"Mars in Scorpio. Three spill. Two remain.", "Grief's fog hides what hope still floats."},
        upright_keywords = {"regret", "grief", "loss", "disappointment", "sorrow", "emotional focus"},
        reversed_keywords = {"acceptance", "healing", "forgiveness", "moving on", "perspective shift", "renewal"},
        upright_fortune = {
            "Three rivers lost to sand. A storm snickers. You really think you'd hold them all?",
            "Loss tallies. The mirror cracks. You're collecting regrets like seashells. Cute.",
            "The heart counts cracks. Mars grins. Drama's your best work, isn't it?"
        },
        reversed_fortune = {
            "The storm retches. Can you find pearls where the wreckage washed ashore?",
            "Mars shrugs, your heart agrees. Grief's a hobby. Time to pick a new one.",
            "The roots map new rivers. The cup will be half full again."
        },
    },
    ["Six of Cups"] = {
        correspondence = {"Sun in Scorpio. Memory sweetens the cup.", "But nostalgia brews both comfort and illusion."},
        upright_keywords = {"nostalgia", "childhood", "memories", "innocence", "comfort", "emotional roots"},
        reversed_keywords = {"living in the past", "clinging", "unrealistic ideals", "emotional stagnation", "unresolved issues", "sentimentality"},
        upright_fortune = {
            "Memories sweeten, but don't overindulge, darling.",
            "Childhood whispers secrets, listen very closely.",
            "Nostalgia's bitter comfort food, savor in moderation."
        },
        reversed_fortune = {
            "Don't drown in yesterday's regrets, sweetie, swim forward.",
            "Past is prologue, not a prescription, write your own story.",
            "Stagnant emotions equal stagnant life, stir the waters."
        },
    },
    ["Seven of Cups"] = {
        correspondence = {"Venus in Scorpio. The dream offers seven doors.", "Choose wrong, and drown in the mirage."},
        upright_keywords = {"choices", "illusions", "dreams", "temptation", "fantasy", "imagination"},
        reversed_keywords = {"clarity", "decision", "groundedness", "reality check", "narrowed focus", "disillusionment"},
        upright_fortune = {
            "Temptation, a siren's song. You, dear, are not a ship.",
            "Fantasy is fun, but don't forget to pay your rent in reality.",
            "Seven doors, seven dramas. Choose wisely... if you can"
        },
        reversed_fortune = {
            "You chose the door with glitter, now you're lost in sparkle.",
            "Clarity arrives, and it's not as exciting as the illusion, sorry.",
            "Narrowed focus: you finally chose a door. Now, about those cat videos..."
        },
    },
    ["Eight of Cups"] = {
        correspondence = {"Saturn in Pisces. The wine has soured.", "You walk away: not from love, but from its ghost."},
        upright_keywords = {"departure", "emotional withdrawal", "searching", "letting go", "inner journey", "dissatisfaction"},
        reversed_keywords = {"fear of change", "stagnation", "avoidance", "stuck emotions", "clinging", "aimlessness"},
        upright_fortune = {
            "The search begins. First clue: your heart.",
            "Letting go is not losing, it's just rearranging your emotional furniture.",
            "Time to walk the solo path. Your only ghost: you.."
        },
        reversed_fortune = {
            "Stagnation's a pond. You're the fish who forgot how to swim.",
            "Clinging to a handful of dust. It's not a good look.",
            "Fear of change? Fancy way to say 'stuck in the mud'."
        },
    },
    ["Nine of Cups"] = {
        correspondence = {"Jupiter in Pisces. The wish granted. The heart swells.", "But beware the fullness that forgets the soul."},
        upright_keywords = {"contentment", "satisfaction", "emotional fulfillment", "pleasure", "wish granted", "gratitude"},
        reversed_keywords = {"smugness", "disappointment", "indulgence", "unmet desires", "superficial joy", "hollow success"},
        upright_fortune = {
            "Your cup runneth over. If you spill it, you clean it.",
            "You've got the pleasure. Don't be a one-hit wonder.",
            "Wish Granted. Now don't get too comfy, the cosmos is watching"
        },
        reversed_fortune = {
            "So full of yourself. Your wish? You forgot it. Oops.",
            "Smugness is not a spiritual practice, darling.",
            "Indulgence isn't fulfillment. Unless you want a tummy ache."
        },
    },
    ["Ten of Cups"] = {
        correspondence = {"Mars in Pisces.\nThe storm has passed.\nThe rainbow arches.", "Harmony, for a heartbeat or a lifetime."},
        upright_keywords = {"harmony", "emotional completion", "family", "joy", "lasting happiness", "shared dreams"},
        reversed_keywords = {"disharmony", "broken connection", "false happiness", "misaligned values", "tension", "emotional instability"},
        upright_fortune = {
            "Family is everything, unless you're a cat, then it's all about the naps.",
            "Joy is contagious, but so is drama. Choose your tribe wisely.",
            "Appreciate the discordant notes that makes the melody interesting."
        },
        reversed_fortune = {
            "Emotional rollercoaster: thrilling, but nauseating. Buckle up!",
            "False happiness or too much candy? After the buzz, you'll crash and burn.",
            "Clashing auras, crystal shoe. Trip and stumble until you find your sole-mate."
        },
    },
    ["Page of Cups"] = {
        correspondence = {"Earth of Water. A fish speaks in riddles.", "You listen, heart open, logic... conveniently drowned."},
        upright_keywords = {"innocence", "emotional curiosity", "messages", "intuition", "creative beginnings", "sensitivity"},
        reversed_keywords = {"emotional immaturity", "creative block", "insecurity", "moodiness", "unrealistic hopes", "avoidance"},
        upright_fortune = {
            "Creative beginnings are like a mermaid's kiss: magical, but slippery.",
            "The universe texts like a crush: cryptic, but worth decoding",
            "Dolphins whisper secrets full of wonder. Don't forget to bring a towel."
        },
        reversed_fortune = {
            "Feeling like a fish out of water? Stop flailing, darling.",
            "Tide of moodiness ebb and flow. Get on your board and surf that wave.",
            "Message in a bottle? You need a map, not dreams."
        },
    },
    ["Knight of Cups"] = {
        correspondence = {"Air of Water. He rides dreams like waves.", "A poet's promise, always just out of reach."},
        upright_keywords = {"romantic offer", "charm", "idealism", "pursuit of dreams", "emotional quest", "imagination"},
        reversed_keywords = {"manipulation", "mood swings", "jealousy", "unrealistic fantasy", "emotional volatility", "seduction"},
        upright_fortune = {
            "Romantic offer arrives. Words are sweet; actions, the chocolate factory.",
            "Pursuit dreams through the long and winding road that leads to your door.",
            "Idealism's a guiding star. Until you see the next shiny thing."
        },
        reversed_fortune = {
            "Fantasy: a tempting trap. Beware of your desire's web.",
            "Jealousy is a green-eyed poison. Have a glass of water.",
            "Inner storm? Grab your anchor, soul-sailor."
        },
    },
    ["Queen of Cups"] = {
        correspondence = {"Water of Water. She listens deeper than words.", "Her gaze stirs tides. Nothing is truly hidden."},
        upright_keywords = {"empathy", "compassion", "intuition", "emotional depth", "nurturing", "inner calm"},
        reversed_keywords = {"emotional overwhelm", "codependency", "suppression", "insecurity", "hypersensitivity", "escapism"},
        upright_fortune = {
            "Your emotions are magic; don't waste them on ghosts..",
            "Don't simply #self-care. Neglect your soul, it'll haunt your sleep.",
            "The depths of your feelings are a mess, but hey, at least you're consistent."
        },
        reversed_fortune = {
            "Your're a hot mess, but no worries. Just kidding, you're totes alone in this mess.",
            "Your emotional storm is not a metaphor. Take cover, and try not to get too wet.",
            "You keep pouring into others. Strange no one's pouring back."
        },
    },
    ["King of Cups"] = {
        correspondence = {"Fire of Water. The sea rages. He does not.", "Emotion held like wine: potent, poised, and masked."},
        upright_keywords = {"emotional balance", "wisdom", "diplomacy", "compassion", "control", "maturity"},
        reversed_keywords = {"emotional repression", "manipulation", "coldness", "instability", "passive-aggression", "detachment"},
        upright_fortune = {
            "Wisdom: knowing when to keep your mouth shut.",
            "Compassion is a superpower. Use it to heal, not enable.",
            "Diplomacy is the art of saying yes without meaning it. Yes?"
        },
        reversed_fortune = {
            "Coldness isn't calmness. One's ice; the other, ocean. Brrr.",
            "Instability's rollercoaster is fun until you have to get out to vomit.",
            "Repressing emotions or holding your breath? Don't turn blue, darling."
        },
    },
}

