-- This file is AUTOMATICALLY GENERATED by generate_card_data.py
-- DO NOT EDIT THIS FILE MANUALLY!

CARD_DATA_SWORDS = {
    ["Ace of Swords"] = {
        correspondence = {"The first cut clears the fog. A truth born raw, shining, and cold with promise."},
        upright_keywords = {"clarity", "truth", "breakthrough", "focus", "mental force", "new idea"},
        reversed_keywords = {"confusion", "misinformation", "self-doubt", "clouded judgment", "misuse of power", "mental fog"},
        upright_fortune = {
            "A truth cuts through. It may sting… but at least now you see it.",
            "A flash of clarity! Careful, lightning rarely explains itself.",
            "The idea lands sharp. Whether it helps or hurts depends on how you hold it."
        },
        reversed_fortune = {
            "Truth knocks. You pretend no one's home.",
            "Sharp thoughts dulled. You brought butter knife in a sword fight.",
            "The blade twists. What was clarity becomes a maze."
        },
    },
    ["Two of Swords"] = {
        correspondence = {"Moon in Libra. The wind stills. Blades cross in silence.", "Peace or paralysis? The heart knows."},
        upright_keywords = {"stalemate", "indecision", "blocked emotions", "difficult choice", "inner conflict", "silence"},
        reversed_keywords = {"avoidance", "overload", "emotional eruption", "bad timing", "hidden truth", "forced hand"},
        upright_fortune = {
            "Your heart whispers. Your mind files a noise complaint.",
            "Peace, or a truce with denial? Either way, no one's moving.",
            "You balanced the blades. Just don't sneeze."
        },
        reversed_fortune = {
            "The decision makes itself. You pretend it didn't.",
            "You avoided the choice. The choice didn't return the favor.",
            "Emotions burst. The swords sigh, they knew this was coming."
        },
    },
    ["Three of Swords"] = {
        correspondence = {"Saturn in Libra. Rain falls through the wound.", "The storm speaks plainly when the heart cannot."},
        upright_keywords = {"heartbreak", "betrayal", "grief", "sorrow", "emotional pain", "harsh truth"},
        reversed_keywords = {"healing", "repression", "denial", "wounds fester", "delayed closure", "emotional numbness"},
        upright_fortune = {
            "The sky cracks. The heart listens. Pain has perfect pitch.",
            "Even spirits wince. Some truths arrive without warning.",
            "The sword lands where it hurts. It never misses."
        },
        reversed_fortune = {
            "The storm fades. But echoes... echoes linger.",
            "Healing creeps in. It prefers the long, awkward route.",
            "The pain hid. You smiled. Neither was convincing."
        },
    },
    ["Four of Swords"] = {
        correspondence = {"Jupiter in Libra.\nSwords laid to rest.\nThe mind exhales.", "Let the hush mend what battle could not."},
        upright_keywords = {"rest", "recovery", "retreat", "contemplation", "mental reset", "sacred pause"},
        reversed_keywords = {"restlessness", "burnout", "no peace", "racing thoughts", "refusal to heal", "disturbed sleep"},
        upright_fortune = {
            "Rest now. The universe promised not to do anything interesting.",
            "Silence heals. Or at least delays your next mistake.",
            "Lie down. Pretend it's part of a grand spiritual plan."
        },
        reversed_fortune = {
            "You said you rested. The bags under your eyes say otherwise.",
            "You skipped the pause. The universe didn't.",
            "The stillness broke. So did your last nerve."
        },
    },
    ["Five of Swords"] = {
        correspondence = {"Venus in Aquarius.\nThe clash ends, but no one's smiling.", "Victory with a hollow echo."},
        upright_keywords = {"conflict", "betrayal", "hollow victory", "selfishness", "tension", "manipulation"},
        reversed_keywords = {"remorse", "resolution", "surrender", "lingering resentment", "lessons learned", "damage control"},
        upright_fortune = {
            "You won. Everyone else left. Victory tastes... complicated.",
            "A hollow triumph echoes longer than silence.",
            "The sword was sharp. So were the consequences."
        },
        reversed_fortune = {
            "You picked peace. Now you miss the drama a little.",
            "An apology lingers… like incense after a ritual gone wrong.",
            "You walked away. Your pride took the long way."
        },
    },
    ["Six of Swords"] = {
        correspondence = {"Mercury in Aquarius.\nThe blade turns toward the horizon.","Not escape, transition cloaked in shadow."},
        upright_keywords = {"transition", "moving on", "mental shift", "journey", "healing", "escape"},
        reversed_keywords = {"stuck", "emotional baggage", "resistance to change", "can't let go", "stagnation", "unfinished business"},
        upright_fortune = {
            "The boat drifts forward. Your baggage waves from shore.",
            "One foot in the past, one in the fog. Balance wisely.",
            "Change whispers. You finally took the ear plugs out."
        },
        reversed_fortune = {
            "You boarded the boat. Then clung to the anchor.",
            "Old wounds unpack themselves. How rude!",
            "You said you moved on. The sharp swords say otherwise."
        },
    },
    ["Seven of Swords"] = {
        correspondence = {"Moon in Aquarius.\nFootsteps fade...", "The truth stays hidden, tucked beneath a cloak of cunning."},
        upright_keywords = {"deception", "strategy", "secrets", "sneakiness", "independence", "mental agility"},
        reversed_keywords = {"truth revealed", "getting caught", "guilt", "poor planning", "confession", "self-deception"},
        upright_fortune = {
            "Not all truths walk in daylight. Some slip through curtains.",
            "Strategy or deceit? The line blurs at midnight.",
            "The shadow moves. It smiles like it knows your secrets."
        },
        reversed_fortune = {
            "Secrets rot when kept too long. Something smells... revealing.",
            "You returned what was taken. But the air still feels uneasy.",
            "The trick backfires. The stars pretend to be surprised."
        },
    },
    ["Eight of Swords"] = {
        correspondence = {"Jupiter in Gemini.\nThe cage is made of thought.", "The key? Whispered by the wind, often unheard."},
        upright_keywords = {"restriction", "trapped", "fear", "paralysis", "mental prison", "helplessness"},
        reversed_keywords = {"liberation", "clarity returns", "new perspective", "self-empowerment", "escape", "fear dissolves"},
        upright_fortune = {
            "Blinded, bound, and somehow still in charge of the drama.",
            "The exit was behind you. Has been for a while.",
            "The cage is real. In your mind. Enjoy."
        },
        reversed_fortune = {
            "Oh look! Clarity! It was under the anxiety all along.",
            "The fog lifts. Try not to walk straight into another one.",
            "The door opens. You hesitate, just for old times sake."
        },
    },
    ["Nine of Swords"] = {
        correspondence = {"Mars in Gemini.\nNight sharpens the mind into blades.", "Sleep flees. Shadows gather to whisper."},
        upright_keywords = {"anxiety", "guilt", "nightmares", "overthinking", "despair", "inner torment"},
        reversed_keywords = {"healing begins", "perspective shift", "facing fears", "insomnia fades", "emotional release", "light breaking through"},
        upright_fortune = {
            "The mind spins. The pillow knows too much.",
            "You asked for signs. They arrived having a party at 3am.",
            "The nightmares are chatty tonight. Did you feed them?"
        },
        reversed_fortune = {
            "You opened the window. The fear slipped out with a dramatic sigh.",
            "The light returns. It's unimpressed by your 3am theories.",
            "Night still knocks. But now you sleep with earplugs."
        },
    },
    ["Ten of Swords"] = {
        correspondence = {"Sun in Gemini.\nThe end is here, cruel and honest.","But from ruin… air stirs once more."},
        upright_keywords = {"betrayal", "rock bottom", "painful end", "defeat", "collapse", "inevitable fall"},
        reversed_keywords = {"recovery", "resurrection", "closure", "lessons learned", "dawn after darkness", "surviving the worst"},
        upright_fortune = {
            "It's dead. Even the spirits have stopped checking for a pulse.",
            "The end came, dramatic and sparkly. The next chapter yawns open.",
            "The blade sings: 'Lesson learned?' You nod. Probably."
        },
        reversed_fortune = {
            "The worst passed. Now what? No, seriously… what now?",
            "The swords slipped out. Try not to trip on them again.",
            "You got back up. No applause, just a knowing breeze."
        },
    },
    ["Page of Swords"] = {
        correspondence = {"Earth of Air.\nEyes sharp, tongue sharper.","A question on every breeze, and no fear of storms."},
        upright_keywords = {"curiosity", "mental spark", "truth-seeker", "vigilance", "fresh ideas", "youthful intellect"},
        reversed_keywords = {"gossip", "scattered thoughts", "overthinking", "spy energy", "manipulation", "mental immaturity"},
        upright_fortune = {
            "Your curiosity found a new hyperfocus. Cosmos apologizes in advance.",
            "Prepare for clarity. It rarely comes with a how-to manual.",
            "Truth may sting, at least now you have something interesting to talk about."
        },
        reversed_fortune = {
            "Your mind's a maze today. The exit sign is in another dimension.",
            "The truth is out there. Are you with Mulder or Scully?",
            "Collecting information? Mostly gossip. Spirits are not bothered."
        },
    },
    ["Knight of Swords"] = {
        correspondence = {"Fire of Air.\nHe charges thought-first, sword aloft.", "Swift, certain, and frequently late to doubt."},
        upright_keywords = {"bold action", "ambition", "unstoppable", "sharp focus", "charging ahead", "swift decisions"},
        reversed_keywords = {"recklessness", "burnout", "cruel words", "tunnel vision", "impulsiveness", "storm without aim"},
        upright_fortune = {
            "Charge, my Don Quixote! Just ensure the destination isn't a windmill.",
            "Action speaks louder than words, especially when those words are 'oops.'",
            "Boldness is your plot. Consequences are merely footnotes."
        },
        reversed_fortune = {
            "Burnout: it's not just for candles anymore.",
            "Tunnel vision means you're missing the obvious. Like the cliff.",
            "You rode in like a storm. Now you're just a gentle breeze of regret."
        },
    },
    ["Queen of Swords"] = {
        correspondence = {"Water of Air.\nShe sees all.", "Her silence cuts cleaner than most speeches. Truth bows before her."},
        upright_keywords = {"clarity", "truth", "independence", "wisdom through pain", "discernment", "no-nonsense"},
        reversed_keywords = {"coldness", "bitterness", "harshness", "emotional walls", "sharp tongue", "clouded judgment"},
        upright_fortune = {
            "Her silence isn't empty; it's just judging you. Accurately.",
            "Truth arrives, uninvited, and settles in. Try to offer it tea.",
            "Clarity descends. It may feel a bit like an interrogation."
        },
        reversed_fortune = {
            "She wields a sword of ice. And your feelings just shivered.",
            "The truth is in there, somewhere, hiding behind a mountain of denial.",
            "Your insight is clouded. Perhaps by a dramatic fog of bitterness."
        },
    },
    ["King of Swords"] = {
        correspondence = {"Air of Air.\nThought distilled into command.", "A ruler of reason: precise, cold, incorruptible."},
        upright_keywords = {"authority", "intellect", "truth", "clear thinking", "fair judgment", "mental mastery"},
        reversed_keywords = {"tyranny", "manipulation", "cold control", "abuse of power", "ruthless logic", "distorted truth"},
        upright_fortune = {
            "Clear thinking, precise cuts. The universe nods in grim approval.",
            "Reason prevails. Emotion was politely asked to leave.",
            "His word is law. Especially when it involves logical deductions and cold stares."
        },
        reversed_fortune = {
            "Logic without heart is just… cold. And probably lonely.",
            "Control is a cruel mistress. You're currently on a very short leash.",
            "Your brilliant ideas have become a tyrannical decree. Good for you."
        },
    },
}

